# Generated by Django 5.0.2 on 2024-02-14 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=56)),
                ('website', models.URLField()),
                ('avatar', models.ImageField(upload_to='authors/avatar/%Y/%m/%d')),
                ('about', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=28)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('like_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('isbn', models.CharField(max_length=128, unique=True)),
                ('language', models.CharField(choices=[('UZ', "O'zbekcha"), ('AR', 'Arabic'), ('EN', 'English'), ('FR', 'French'), ('RU', 'Russian')], max_length=14)),
                ('page', models.IntegerField()),
                ('cover', models.ImageField(upload_to='books/cover/%Y/%m/%d')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('genre', models.ManyToManyField(related_name='books', to='books.bookgenre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
