# Generated by Django 5.0.2 on 2024-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='book', unique=True),
            preserve_default=False,
        ),
    ]
