# Generated by Django 5.0.2 on 2024-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenre',
            name='description',
            field=models.TextField(default='genre'),
            preserve_default=False,
        ),
    ]
