# Generated by Django 5.0.2 on 2024-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default/default_user.jpg', upload_to='books/cover/%Y/%m/%d'),
        ),
    ]
